name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    name: Test on Linux OTP ${{matrix.otp}} and ${{matrix.os}}

    strategy:
      matrix:
        otp: ['26', '27']
        os: [ubuntu-latest]
        arch:
          - amd64
          - arm64

    runs-on: ubuntu-22.04${{ matrix.arch == 'arm64' && '-arm' || '' }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: '3.22.1'

    - name: Compile
      run: make

    - name: Run tests
      run: make tests

  mac:
    name: Test on Mac ${{matrix.otp}} and ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - macos-15
        rebar3:
          - '3.23.0'
        otp:
          - '27'
          - '26'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Homebrew cache
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew/
            ~/Library/Caches/Homebrew/downloads/
          key: brew-${{ matrix.os }}-${{ matrix.otp  }}

      - name: prepare
        run: |
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          brew install erlang@${{ matrix.otp }}
          echo "$(brew --prefix erlang@${{ matrix.otp }})/bin" >> $GITHUB_PATH

      - name: build
        run: |
          wget https://github.com/erlang/rebar3/releases/download/${{ matrix.rebar3 }}/rebar3
          sudo mv rebar3 /usr/local/bin/ && sudo chmod +x /usr/local/bin/rebar3
          erl -eval 'erlang:display(erlang:system_info(system_version)),halt()'
          # run sudo for getting coredump
          make tests
