name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test on OTP ${{matrix.otp}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        otp: ['26', '27']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Erlang
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        rebar3-version: '3.22.1'

    - name: Compile
      run: make

    - name: Run tests
      run: make tests
